CREATE TABLE inventors (
  Firstname varchar(255) NULL,
  Middlename varchar(255) NULL,
  Lastname varchar(255) NULL,
  Street varchar(255) NULL,
  City varchar(255) NULL,
  State varchar(255) NULL,
  Country varchar(255) NULL,
  Zipcode varchar(255) NULL,
  Latitude varchar(255) NULL,
  Longitude varchar(255) NULL,
  InvSeq int(11) NULL,
  Patent varchar(255) NULL,
  AppYear int(11) NULL,
  ApplyYear int(11) NULL,
  PubYear int(11) NULL,
  AppDate varchar(255) NULL,
  Assignee varchar(255) NULL,
  AsgNum varchar(255) NULL,
  Class varchar(255) NULL,
  Coauthor varchar(255) NULL,
  Invnum varchar(255) NULL,
  Invnum_N varchar(255) NULL,
  Record_ID varchar(255) NOT NULL,
  Inventor_ID varchar(255) NULL,
PRIMARY KEY(Record_ID)
) ENGINE=InnoDB CHARSET=utf8;
